### ISSUE TITLE
ejs with v0.11.14   Error: Identifier 'rethrow' has already been declared   

### ISSUE THREAD

**Issue by desenmeng** [tj/ejs#200]
``` bash
$ node --version 
$ v0.11.14
```

some.js

``` javascript
var ejs = require('ejs'); 
```

``` bash
$ node --harmony some.js
```

Error

```
SyntaxError: Identifier 'rethrow' has already been declared
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mdemo/work/code/lark-views/ejs.js:9:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

**Comment by mde** [comment]
This repo is for the unmaintained v1 of the library. Current work on EJS is happening here: https://github.com/mde/ejs (I see you've posted this over there, too. This is just a note for people for future reference.)
