### ISSUE TITLE
Nodejs can work well in v1.0.0, but failure in v2.3.1

### ISSUE THREAD

**Issue by wanzhou** [tj/ejs#201]
in package.json : "ejs": "latest", v2.3.1 is installed. When I exec node, it prompts an error.
Error: ENOENT, no such file or directory '/includes/list.html'
at Object.fs.openSync (fs.js:438:18)
   at Object.fs.readFileSync (fs.js:289:15)
   at includeSource (/Users/xxx/node_modules/ejs/lib/ejs.js:194:17)
   at /Users/xxx/node_modules/ejs/lib/ejs.js:512:24
   at Array.forEach (native)
   at Object.Template.generateSource (/Users/xxx/node_modules/ejs/lib/ejs.js:493:15)
   at Object.Template.compile (/Users/xxx/node_modules/ejs/lib/ejs.js:416:12)
   at Object.compile (/Users/xxx/node_modules/ejs/lib/ejs.js:288:16)
   at handleCache (/Users/xxx/node_modules/ejs/lib/ejs.js:147:16)
   at View.exports.renderFile [as engine](/Users/xxx/node_modules/ejs/lib/ejs.js:348:14) 
The same code, work well in ejs@1.0.0, but failure in ejs@v2.3.1
| v2.3.1
|- Jakefile
|- README.md
|- ejs.js
|- ejs.min.js
|- lib
|- package.json test

| v1.0.0
|- History.md
|- Readme.md
|- ejs.js
|- examples
|- lib
|- support
|- Makefile
|- benchmark.js
|- ejs.min.js
|- index.js
|- package.json
|- test

**Comment by mde** [comment]
We're going to need a little more information before we can help you with this. This doesn't show how you're using the EJS API.
