### ISSUE TITLE
Cant include partials

### ISSUE THREAD

**Issue by andreiverse** [tj/ejs#241]
i receive this:
```js
Error: Could not find the include file "../partials/header"
    at getIncludePath (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:162:13)
    at includeSource (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:306:17)
    at /rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:678:15)
    at Template.compile (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:557:12)
    at Object.compile (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:389:16)
    at handleCache (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:212:18)
    at tryHandleCache (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:251:16)
    at View.exports.renderFile [as engine] (/rbd/pnpm-volume/a1160d3a-d6de-4dc9-be2e-8d89033ae156/node_modules/.registry.npmjs.org/ejs/2.6.1/node_modules/ejs/lib/ejs.js:482:10)
```

**Comment by Jobfreedom** [comment]
// For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
