### ISSUE TITLE
data passed to ejs.render not defined, causes error

### ISSUE THREAD

**Issue by robogeek** [tj/ejs#67]
I have replicated a problem using the example code off the front page of this project.  Data passed into ejs.render are throwing an error when referenced in a template.

Code:

``` javascript
var ejs = require('ejs');
var util = require('util');

// var tmpl = "<p><%=: users | map:'name' | join %></p>"
var tmpl = "<ul> <% users.forEach(function(user){ %> <li><%= user.name %></li> <% }) %> </ul>";
util.log(ejs.render(tmpl, {
    users: [
      { name: 'tj' },
      { name: 'mape' },
      { name: 'guillermo' }
    ]
}));
```

Error:

```
tippy:gulp davidherron$ node tt.js 

undefined:24
  throw err;
        ^
ReferenceError: ejs:1
 >> 1| <ul> <% users.forEach(function(user){ %> <li><%= user.name %></li> <% }) %> </ul>

users is not defined
    at eval (eval at <anonymous> (/Users/davidherron/node_modules/ejs/lib/ejs.js:198:12))
    at exports.compile (/Users/davidherron/node_modules/ejs/lib/ejs.js:200:15)
    at Object.exports.render (/Users/davidherron/node_modules/ejs/lib/ejs.js:235:13)
    at Object.<anonymous> (/Users/davidherron/boilerplate/gulp/tt.js:6:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by ruanjiayou** [comment]
首页传变量有这个问题，其他页面没有。 ReferenceError   变量 is undefined

**Comment by mde** [comment]
This version of EJS is no longer supported. The current version on NPM is here: https://github.com/mde/ejs
